version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./app:/app
      - postgres_static_data:/vol/web
    ports:
      - 8000:8000
    image: app:django
    container_name: ecommerce_container
    command: >
         sh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ecommerce_db
      - DB_USER=postgres
      - DB_PASS=7034
  db:
    image: postgres:latest
    volumes:
      - ecommerce_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7034
    container_name: ecommerce_db
volumes:
  ecommerce_db:
  postgres_static_data:

